DROP TABLE WEATHER_STATION;
CREATE TABLE WEATHER_STATION(STATIONID VARCHAR PRIMARY KEY,USAF VARCHAR,WBAN VARCHAR,NAME VARCHAR,COUNTRY VARCHAR,STATE VARCHAR,CALL VARCHAR,ELEVATION FLOAT,BEGINDATE VARCHAR,ENDDATE VARCHAR);
SELECT AddGeometryColumn ('postgres','weather_station','geolocation',4326,'POINT',2);
