CREATE TABLE WEATHER_STATIONS(STATIONID VARCHAR PRIMARY KEY,USAF VARCHAR,WBAN VARCHAR,NAME VARCHAR,COUNTRY VARCHAR,STATE VARCHAR,CALL VARCHAR,LOCATION POINT,ELEVATION FLOAT,BEGINDATE VARCHAR,ENDDATE VARCHAR);

