
-- in the node serving kafka streams
DROP TABLE POSTGRES.WEATHER_STATION;
CREATE TABLE POSTGRES.WEATHER_STATION(STATIONID VARCHAR PRIMARY KEY,USAF VARCHAR,WBAN VARCHAR,NAME VARCHAR,COUNTRY VARCHAR,STATE VARCHAR,CALL VARCHAR,ELEVATION FLOAT,BEGINDATE VARCHAR,ENDDATE VARCHAR);
SELECT AddGeometryColumn ('postgres','weather_station','geolocation',4326,'POINT',2);



-- in node serving the front end
DROP TABLE POSTGRES.FLIGHT;
CREATE TABLE POSTGRES.FLIGHT (FLIGHT_ID VARCHAR NOT NULL,INFO JSON NOT NULL);

